import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "./fonts";
import { ThemeProvider } from "@/components/context/ThemeContext";
import { AmplitudeProvider } from "@/components/context/AmplitudeContext";
import { AuthProvider } from "@/components/context/AuthContext";
import { NavBar } from "@/components/NavBar";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased bg-background text-foreground`}
      >
        <AmplitudeProvider>
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NavBar />
              <main>{children}</main>
              <Toaster />
            </ThemeProvider>
          </AuthProvider>
        </AmplitudeProvider>
      </body>
    </html>
  );
}
