import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { geistMono, geistSans } from "./fonts";
import AmplitudeContextProvider from "@/components/context/AmplitudeContext";
import { AuthProvider } from "@/components/context/AuthContext";
import { NavBar } from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased bg-background text-foreground`}
      >
        <AmplitudeContextProvider>
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NavBar />
              <main>{children}</main>
            </ThemeProvider>
          </AuthProvider>
        </AmplitudeContextProvider>
      </body>
    </html>
  );
}
